--- 
applications: 
  dist/wgrus-polyglot-inventory/wgrus-inventory.zip: 
    name: wgrus-inventory
    framework: 
      name: standalone
      info: 
        mem: 64M
        description: Standalone Application
        exec: 
    runtime: java
    command: java $JAVA_OPTS -jar wgrus-polyglot-inventory_2.9.1-0.1.0-SNAPSHOT.jar
    url: wgrus-inventory.cloudfoundry.com
    mem: 128M
    instances: 1
    services: 
      inventory: 
        type: redis
